#### 什么是异常

```java
什么是异常：在程序运行过程中，意外发生的情况，背离我们程序本身的意图的表现，都可以理解为异常。

编译期间的错误：编译器会协助修订

运行期间的错误：轻则编译错误，重则程序崩溃

程序中的异常：
1.使用空的对象引用调用方法;
2.数组访问时下标越界;
3.算数运算除数为0;
4.类型转换时无法正常转型       
```

#### 异常分类

```java
异常根类：Throwable
一、Error1、Error是程序无法处理的错误，表示运行应用程序小红比较严重问题常见问题
-VirtualMachineError（虚拟机错误）
-OutOfMemoryError（内存溢出错误）
-TheadDeath（线程死锁）
二、Exception是程序本身可以处理的异常，异常处理通常指针对这种类型异常的处理
1、Unchecked Exception（非检查异常）——根类RuntimeException-NullpointerException（空指针异常）
-ArrayIndexOfBoundsException（数组下标越界异常）
-ArithmeticException（算数异常）
-ClassCastException（类型转换异常）
2、Checked Exception（检查异常）
```

#### 异常处理

```java
异常处理
1、抛出异常 2、捕获异常
通常通过5个关键字：try,catch,finally,throw,throws
捕获异常：
try:执行可能产生异常的代码
catch：捕获异常
finally：无论是否发生异常代码总能执行
声明异常：
throws：声明可能抛出的异常
抛出异常：
throw：手动抛出异常
```

#### try-catch-finally

```java
语法：
try{
	//代码段1
	//产生异常的代码段2
     }catch(异常类型 ex){
	//对异常进行处理的代码段3
     }finally{
	//代码段四
	}
1、try块用于捕获异常
2、catch块用于处理try捕获到的异常
3、finally块无论是否发生异常代码总能执行
4、try块后可以接零个或者多个catch块，如果没有catch块，则必须跟一个finally块进行使用
5、catch和finally没有try的加入无法单独行动
```

```java
try{
//这里面是可能出错的代码
}catch（Exception e）{
e.printStackTrace();//这个语句是用来输出异常的位置和信息，输出位置不固定
//使用catch捕获try里可能出现的异常，（Exception e）是异常的类型
//捕获异常后，语句块执行
}finally {
//这里的代码块无论是否捕获都会执行
}  
```

#### 多重catch结构

```java
1. 一个try块后跟的多个catch块，其参数不能是同类型异常。当一个catch块执行后，其它catch块就不会执行了。
2. 由于比较难保证catch块覆盖所有异常情况，所以建议最后一个catch块的参数是Exception的对象（例：Exception e）。注意这种catch块要放到最后，不然其下的其它catch块不可能执行。 
```

```java
//定义两个整数，接受键盘输入，输出两个数的商
Scanner input = new Scanner(System.in);
try {
    int one=input.nextInt();
    int two=input.nextInt();
    System.out.println(one/two);
}catch (ArithmeticException e){ //ArithmeticException 算数异常
	System.exit(1);//终止程序运行
    System.out.println("除数不能为零!");
    e.printStackTrace();             //这个语句是用来输出异常的位置和信息，输出位置不固定
}catch (InputMismatchException e){   // 输入异常
    System.out.println("请输入整数!");
    e.printStackTrace();
}catch (Exception e){ // 捕获子类型中无法捕获的异常信息
    System.out.println("出错了!");
    e.printStackTrace();
}finally {
    System.out.println("程序结束!");
    //这里的代码块无论是否捕获都会执行
}
```

#### finally

```java
finally只能有一个

终止执行：
System.out.exit(1);
1、表示程序终止运行，所有后面的程序都不会再执行
2、括号内的值，为非零表示非正常退出，0表示正常退出

终止当前正在运行的虚拟机
System.exit(1) 表示异常导致的程序终止
System.exit(0) 表示程序正常终止
非0是异常，终止虚拟机      
```

#### return

```java
在一个方法中，程序遇见return，就会退出当前方法，我们经使用return返回相应的数据；
但如果一个方法中使用了try-catch-finally方式，并使用return返回数据时就要注意了：
在try-catch-finally中，finally是无论try执行或是catch执行，最后都必然执行finally中的内容！return关键字都无法阻止其发生，这是finally的特性！
在try中有return 10；
在catch中有return 20；
在finally中有return 30；
finally中的return会覆盖前面的返回值，无论怎么执行，最终都是返回30。

程序遇见return，表示当前方法执行完成，就会退出方法！但是在try-catch-finally中比较特殊，退出方法之前要先执行finally块中的语句。       
```

#### throws

```java
如果一个方法可能会出现异常，但没有能力处理这种异常，可以在方法声明处用throws子句来声明抛出何种类型的异常。谁调用这个方法则谁处理抛出的异常。后续的方法在处理异常时可以继续抛出，也可以使用try-catch-finally结构进行异常捕获处理，在进行异常捕获处理时，可以使用 多catch块 结构。

通过throws抛出异常时，针对可能出现的多种异常情况，解决方案：
1、throws后面接多个异常类型，中间用逗号分隔
2、throws后面接Exception

RuntimeException及其子类都是UncheckedException（非检查型异常）。当throws非检查型异常时，在调用方法处，编译器不会强制要求对非检查型异常进行处理。
```

#### throw

```java
1. throw用来抛出一个异常对象，例如：throw new IOException();

2. throw抛出的只能是Throwable或者是其子类的实例对象。

3. throw抛出异常对象的处理方案:
1）自己抛出自己处理，通过try-catch包含throw语句。
2）用throws往上抛，调用者可以try-catch处理或者继续往上抛。throws抛出异常类型时，要抛出与throw对象相同的类型或者其父类。（例如：throw new Exception(); 那么可以throws Throwable）

4. 如果throw抛出的异常对象为InputMismatchException这样的非检查型异常，编译器不会强制要求必须进行异常处理。

5. 在程序中使用throw主动抛出异常对象的目的
1）规避可能出现的风险
2）完成程序逻辑       
```

#### throw总结

```java
throw抛出异常对象的处理方案
* 1.通过try..catch包含throw语句--自己抛出的异常自己处理
* 2.通过throws在方法声明处抛出可能出现的异常类型,
* 谁调用谁用try-catch处理-可以自己处理,也可以继续上抛
* 3.throws可以抛出throw对象相同的类型或其父类,不可以抛出其子类
* 4.throw手动抛出的异常不应该用非检查类型,因为编译器不提示  
    
public static void testAge() throws Throwable{
    Scanner input = new Scanner(System.in);
    int age = input.nextInt();
    if(age > 80 || age < 18){
        throw new Exception("未成年和老年人不接待。")
    }else{
        System.out.println("欢迎光临。")
    }
}
```

#### 自定义异常

```java
自定义异常
使用Java内置的异常类可以描述在编译时出现的大部分异常情况。
也可以通过自定义异常描述特定业务产生的异常类型。
所谓自定义异常，就是定义一个类，去继承Throwable类或者它的子类

public class HotelAgeException extends Exception{
	public HotelAgeException (){
		super("18岁以下住店必须由亲友陪同"); 
	}
}
方法中调用时则
throw new HotelAgeException();
在创建构造方法的时候调用父类的带参构造方法
e.getMessage()方法可以显示异常信息              
```

#### 异常链

```java
异常链：有时我们会捕获一个异常后再抛出异常
异常链就是一个异常接着一个异常，最后输出的异常就只有最后一个
如果想要把前面所有异常都输出的话，则需要输出的异常就只有最后一个。
1、通过构造方法对旧异常对象的获取
Throwable(String message, Throwable cause) -- 保留底层异常的异常信息。
2、通过initCause(Throwable cause)方法（一个异常的信息来初始化一个新的异常）用来获取原始异常的描述信息，其中cause是原始异常的对象 
```

```
public class TryDemoFour {
    public static void main(String[] args) {
        try {
            teatThree();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static void teatOne() throws AgeException {
        throw new AgeException(); //原始异常
    }

    public static void teatTwo() throws Exception {
        try {
            teatOne(); //处理原始异常
        } catch (AgeException e) {
            throw new Exception("新异常1",e);
        }
    }

    public static void teatThree() throws Exception {
        try {
            teatTwo(); //处理异常1
        } catch (Exception e) {
//            throw new Exception("新异常2",e);
            Exception e1 = new Exception("新异常2");
            e1.initCause(e);
            throw e1;
        }
    }
}
```

### 总结

```java
try-catch-finally实际应用中的经验和总结：
1. 处理运行时异常时，采用逻辑去合理规避同时辅助try-catch处理；
2. 在多个catch块后面，可以加一个catch(Exception)来处理可能会被遗漏的异常；
3. 对于不确定的代码，也可以加上try-catch，处理潜在的异常；
4. 尽量去处理异常，切忌只是简单的调用printStackTrace()去打印输出；
5. 具体如何处理异常，要根据不同的业务需求和异常类型去决定；
6. 尽量添加finally语句去释放占用的资源，如打开的文件对象等。       
```